manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: dactylcc
      url-base: https://github.com/cgoates
  projects:
    - name: zmk
      remote: dactylcc
      revision: main
      import: app/west.yml
  self:
    path: config
